apiVersion: v2
name: covenant
version: 0.3.0
description: Identity and access management system using mystical covenant architecture
home: https://github.com/runik-spells
sources:
  - https://github.com/runik-spells/runik-system
maintainers:
  - name: namen malkav
    email: namenmalkav@gmail.com
  - name: laaledesiempre
    email: laaledesiempre@disroot.org
