{{/*kast - Kubernetes arcane spelling technology
Copyright (C) 2023 namenmalkav@gmail.com
Licensed under the GNU GPL v3. See LICENSE file for details.

NEW: ApplicationSet-based librarian
Generates 1 ApplicationSet per chapter instead of individual Applications
ApplicationSets auto-discover spells via git files generator
*/}}

{{- $spellbook := dict "appParams" $.Values.appParams }}
{{- $_ := set $spellbook "name" (default $.Release.Name $.Values.name) }}

{{/* Load book index */}}
{{- $path := printf "bookrack/%s/index.yaml" (default .Release.Name .Values.name) }}
{{- if .Files.Glob $path }}
  {{- $default := .Files.Get $path | fromYaml }}
  {{- $_ := mergeOverwrite $spellbook $default }}
{{- end }}

{{/*
  PASS 1: Consolidate appendix globally (book → chapter → spells)
  This is the SAME as before, but now we pre-render it into ApplicationSet templates
*/}}
{{- $globalAppendix := deepCopy (default dict $spellbook.appendix) }}

{{/* Collect appendix from chapters and all spell files */}}
{{- range $chapterName := $spellbook.chapters }}
  {{- $pathChapter := print "bookrack/" $spellbook.name "/" $chapterName "/index.yaml" }}
  {{- if $.Files.Glob $pathChapter }}
    {{- $chapterDef := $.Files.Get $pathChapter | fromYaml }}
    {{- if $chapterDef.appendix }}
      {{- $_ := mergeOverwrite $globalAppendix (deepCopy $chapterDef.appendix) }}
    {{- end }}
  {{- end }}

  {{/* Collect appendix from all files in chapter */}}
  {{- $path := print "bookrack/" $spellbook.name "/" $chapterName "/*.y*ml" }}
  {{- range $spellPath, $_ := $.Files.Glob $path }}
    {{- if not (eq $spellPath (print "bookrack/" $spellbook.name "/" $chapterName "/index.yaml")) }}
      {{- $spellDefinition := ($.Files.Get $spellPath | fromYaml) }}
      {{- if $spellDefinition.appendix }}
        {{- $_ := mergeOverwrite $globalAppendix (deepCopy $spellDefinition.appendix) }}
      {{- end }}
    {{- end }}
  {{- end }}
{{- end }}

{{/*
  PASS 2: Generate ApplicationSets (one per chapter)
  Each ApplicationSet will auto-discover spells via git files generator
*/}}
{{ range $chapterName := $spellbook.chapters }}
  {{- $chapter := dict "name" $chapterName }}
  {{- $chapterLocalAppendix := dict }}

  {{/* Build trinketsByKey AND defaultTrinket for this chapter: book < chapter */}}
  {{- $chapterTrinketsByKey := dict }}
  {{- $chapterDefaultTrinket := dict }}
  {{- $chapterAppParams := dict }}

  {{/* Initialize with book-level defaults */}}
  {{- if $spellbook.defaultTrinket }}
    {{- $chapterDefaultTrinket = deepCopy $spellbook.defaultTrinket }}
  {{- end }}

  {{/* Initialize appParams with book-level defaults */}}
  {{- if $spellbook.appParams }}
    {{- $chapterAppParams = deepCopy $spellbook.appParams }}
  {{- end }}

  {{- if $spellbook.trinkets }}
    {{- range $name, $trinket := $spellbook.trinkets }}
      {{- if $trinket.key }}
        {{- $_ := set $chapterTrinketsByKey $trinket.key (deepCopy $trinket) }}
      {{- end }}
    {{- end }}
  {{- end }}

  {{/* Load chapter definition */}}
  {{- $pathChapter := print "bookrack/" $spellbook.name "/" $chapterName "/index.yaml" }}
  {{- if $.Files.Glob $pathChapter }}
    {{- $chapterDef := $.Files.Get $pathChapter | fromYaml }}
    {{- $chapter = $chapterDef }}
    {{- if not $chapter.name }}
      {{- $_ := set $chapter "name" $chapterName }}
    {{- end }}

    {{/* Store chapter localAppendix for override */}}
    {{- if $chapterDef.localAppendix }}
      {{- $chapterLocalAppendix = deepCopy $chapterDef.localAppendix }}
    {{- end }}

    {{/* Merge chapter.defaultTrinket (book < chapter) */}}
    {{- if $chapterDef.defaultTrinket }}
      {{- $_ := mergeOverwrite $chapterDefaultTrinket (deepCopy $chapterDef.defaultTrinket) }}
    {{- end }}

    {{/* Merge chapter.appParams (book < chapter) */}}
    {{- if $chapterDef.appParams }}
      {{- $_ := mergeOverwrite $chapterAppParams (deepCopy $chapterDef.appParams) }}
    {{- end }}

    {{/* Merge chapter.trinkets to chapterTrinketsByKey */}}
    {{- if $chapterDef.trinkets }}
      {{- range $name, $trinket := $chapterDef.trinkets }}
        {{- if $trinket.key }}
          {{- if hasKey $chapterTrinketsByKey $trinket.key }}
            {{- $_ := mergeOverwrite (index $chapterTrinketsByKey $trinket.key) (deepCopy $trinket) }}
          {{- else }}
            {{- $_ := set $chapterTrinketsByKey $trinket.key (deepCopy $trinket) }}
          {{- end }}
        {{- end }}
      {{- end }}
    {{- end }}
  {{- end }}

  {{/* Create final appendix for this chapter: global < chapterLocal */}}
  {{- $finalAppendix := deepCopy $globalAppendix }}
  {{- if $chapterLocalAppendix }}
    {{- $_ := mergeOverwrite $finalAppendix (deepCopy $chapterLocalAppendix) }}
  {{- end }}

  {{/* Build lexicon and cards with .name ensured */}}
  {{- $lexicon := dict }}
  {{- if $finalAppendix.lexicon }}
    {{- range $name, $lexiconDef := $finalAppendix.lexicon }}
      {{- if not (hasKey $lexiconDef "name") }}
        {{- $_ := set $lexiconDef "name" $name }}
      {{- end }}
      {{- $lexicon = set $lexicon $name $lexiconDef }}
    {{- end }}
  {{- end }}

  {{- $cards := dict }}
  {{- if $finalAppendix.cards }}
    {{- range $cardKey, $cardDef := $finalAppendix.cards }}
      {{- if not (hasKey $cardDef "name") }}
        {{- $_ := set $cardDef "name" $cardKey }}
      {{- end }}
      {{- $cards = set $cards $cardKey $cardDef }}
    {{- end }}
  {{- end }}

  {{/* Clean spellbook (remove AppParams, etc.) */}}
  {{- $cleanSpellbook := merge (dict "spellbook" (deepCopy $spellbook)) }}
  {{- $_ := unset $cleanSpellbook.spellbook "appParams" }}
  {{- $_ := unset $cleanSpellbook.spellbook "summon" }}
  {{- $_ := unset $cleanSpellbook.spellbook "kaster" }}
  {{- $_ := unset $cleanSpellbook.spellbook "appendix" }}
  {{- $_ := unset $cleanSpellbook.spellbook "localAppendix" }}

  {{/* Repository config */}}
  {{- $repoURL := default "git@github.com:the-yaml-life/proto-the-yaml-life.git" $spellbook.repository }}
  {{- $revision := default "main" $spellbook.revision }}

  {{/* Serialize trinketsByKey for templatePatch */}}
  {{- $trinketKeysJson := keys $chapterTrinketsByKey | join "," }}
---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: {{ $spellbook.name }}-{{ $chapterName }}-apps
  namespace: {{ default "argocd" $spellbook.argocdNamespace }}
  labels:
    app.kubernetes.io/name: {{ $spellbook.name }}
    app.kubernetes.io/instance: {{ $.Release.Name }}
    app.kubernetes.io/managed-by: {{ $.Release.Service }}
    kast.io/book: {{ $spellbook.name }}
    kast.io/chapter: {{ $chapterName }}
  annotations:
    argocd.argoproj.io/sync-wave: "10"
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=zero"]

  generators:
    - git:
        repoURL: {{ $repoURL }}
        revision: {{ $revision }}
        files:
          - path: "bookrack/{{ $spellbook.name }}/{{ $chapterName }}/*.yaml"
          - path: "bookrack/{{ $spellbook.name }}/{{ $chapterName }}/index.yaml"
            exclude: true
        pathParamPrefix: file

  template:
    metadata:
      name: '{{`{{ .name }}`}}'
      namespace: {{ default "argocd" $spellbook.argocdNamespace }}
    spec:
      project: {{ default (default (default $spellbook.projectName $chapter.projectName) $spellbook.name) ($chapter.projectName) }}
      destination:
        server: {{ default "https://kubernetes.default.svc" "" }}
        namespace: '{{`{{ default .name .namespace }}`}}'
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
          - PrunePropagationPolicy=foreground
          - PruneLast=true

  templatePatch: |
    metadata:
      {{`{{- if .appParams }}`}}
      {{`{{- with .appParams.customFinalizers }}`}}
      finalizers:
        '{{`{{- toYaml . | nindent 8 }}`}}'
      {{`{{- end }}`}}
      {{`{{- with .appParams.annotations }}`}}
      annotations:
        '{{`{{- toYaml . | nindent 8 }}`}}'
      {{`{{- end }}`}}
      {{`{{- end }}`}}
    spec:
      sources:
        # Source 1: Primary source (custom chart OR defaultTrinket - summon)
        {{`{{- if or .chart .path }}`}}
        # Custom chart
        - repoURL: '{{`{{ .repository }}`}}'
          {{`{{- if .chart }}`}}
          chart: '{{`{{ .chart }}`}}'
          {{`{{- else }}`}}
          path: '{{`{{ .path }}`}}'
          {{`{{- end }}`}}
          targetRevision: '{{`{{ .revision }}`}}'
          {{`{{- if not (and .appParams .appParams.noHelm) }}`}}
          helm:
            {{`{{- if and .appParams .appParams.skipCrds }}`}}
            skipCrds: true
            {{`{{- end }}`}}
            values: |
              {{`{{- if .values }}`}}
              '{{`{{- toYaml .values | nindent 14 }}`}}'
              {{`{{- end }}`}}
              {{`{{- if and .appParams .appParams.bookData }}`}}
              {{- toYaml $cleanSpellbook | nindent 14 }}
              chapter:
              {{- toYaml $chapter | nindent 16 }}
              lexicon:
              {{- toYaml $lexicon | nindent 16 }}
              {{- if $cards }}
              cards:
              {{- toYaml $cards | nindent 16 }}
              {{- end }}
              {{`{{- end }}`}}
          {{`{{- end }}`}}
        {{`{{- else }}`}}
        # defaultTrinket (summon)
        - repoURL: {{ $chapterDefaultTrinket.repository }}
          {{- if $chapterDefaultTrinket.chart }}
          chart: {{ $chapterDefaultTrinket.chart }}
          {{- else }}
          path: {{ $chapterDefaultTrinket.path }}
          {{- end }}
          targetRevision: {{ $chapterDefaultTrinket.revision }}
          helm:
            values: |
              {{`{{- $values := . }}`}}
              {{`{{- $_ := unset $values "runes" }}`}}
              {{`{{- $_ := unset $values "appParams" }}`}}
              {{`{{- $_ := unset $values "appendix" }}`}}
              {{`{{- $_ := unset $values "localAppendix" }}`}}
              {{- range $key, $_ := $chapterTrinketsByKey }}
              '{{`{{- $_ := unset $values "`}}{{ $key }}{{`" }}`}}'
              {{- end }}
              '{{`{{- toYaml $values | nindent 14 }}`}}'
              {{- toYaml $cleanSpellbook | nindent 14 }}
              chapter:
              {{- toYaml $chapter | nindent 16 }}
              lexicon:
              {{- toYaml $lexicon | nindent 16 }}
              {{- if $cards }}
              cards:
              {{- toYaml $cards | nindent 16 }}
              {{- end }}
        {{`{{- end }}`}}
        # Sources 2..N: Dynamic trinket detection
        {{- range $trinketKey, $trinket := $chapterTrinketsByKey }}
        {{`{{- if .`}}{{ $trinketKey }}{{` }}`}}
        - repoURL: {{ $trinket.repository }}
          {{- if $trinket.chart }}
          chart: {{ $trinket.chart }}
          {{- else }}
          path: {{ $trinket.path }}
          {{- end }}
          targetRevision: {{ $trinket.revision }}
          helm:
            values: |
              {{- if eq $trinketKey "glyphs" }}
              glyphs:
                '{{`{{- toYaml .glyphs | nindent 16 }}`}}'
              {{- else }}
              {{ $trinketKey }}:
                '{{`{{- toYaml .`}}{{ $trinketKey }}{{` | nindent 16 }}`}}'
              {{- end }}
              {{- toYaml $cleanSpellbook | nindent 14 }}
              chapter:
              {{- toYaml $chapter | nindent 16 }}
              lexicon:
              {{- toYaml $lexicon | nindent 16 }}
              {{- if and (eq $trinketKey "tarot") $cards }}
              cards:
              {{- toYaml $cards | nindent 16 }}
              {{- end }}
        {{`{{- end }}`}}
        {{- end }}
        # Runes support (additional sources)
        {{`{{- range .runes }}`}}
        {{`{{- if or .chart .path }}`}}
        - repoURL: '{{`{{ .repository }}`}}'
          {{`{{- if .chart }}`}}
          chart: '{{`{{ .chart }}`}}'
          {{`{{- else }}`}}
          path: '{{`{{ .path }}`}}'
          {{`{{- end }}`}}
          targetRevision: '{{`{{ .revision }}`}}'
          {{`{{- if not (and .appParams .appParams.noHelm) }}`}}
          helm:
            {{`{{- if and .appParams .appParams.skipCrds }}`}}
            skipCrds: true
            {{`{{- end }}`}}
            values: |
              {{`{{- if .values }}`}}
              '{{`{{- toYaml .values | nindent 14 }}`}}'
              {{`{{- end }}`}}
          {{`{{- end }}`}}
        {{`{{- else }}`}}
        - repoURL: {{ $chapterDefaultTrinket.repository }}
          {{- if $chapterDefaultTrinket.chart }}
          chart: {{ $chapterDefaultTrinket.chart }}
          {{- else }}
          path: {{ $chapterDefaultTrinket.path }}
          {{- end }}
          targetRevision: {{ $chapterDefaultTrinket.revision }}
          helm:
            values: |
              {{`{{- if .values }}`}}
              '{{`{{- toYaml .values | nindent 14 }}`}}'
              {{`{{- end }}`}}
        {{`{{- end }}`}}
        {{`{{- end }}`}}
      syncPolicy:
        {{/* managedNamespaceMetadata - spell override only (no default) */}}
        {{`{{- if and .appParams .appParams.managedNamespaceMetadata }}`}}
        managedNamespaceMetadata:
          '{{`{{- toYaml .appParams.managedNamespaceMetadata | nindent 10 }}`}}'
        {{`{{- end }}`}}
        {{/* automated - render unless book/chapter/spell disables */}}
        {{- if $chapterAppParams.disableAutoSync }}
        {{/* Book or chapter has disableAutoSync - check if spell overrides */}}
        {{`{{- if .appParams }}`}}
        {{`{{- if hasKey .appParams "disableAutoSync" }}`}}
        {{`{{- if not .appParams.disableAutoSync }}`}}
        {{/* Spell explicitly enables auto-sync (overriding book/chapter) */}}
        {{`{{- if .appParams.syncPolicy.automated }}`}}
        automated:
          '{{`{{- toYaml .appParams.syncPolicy.automated | nindent 10 }}`}}'
        {{`{{- else }}`}}
        automated:
          prune: true
          selfHeal: true
        {{`{{- end }}`}}
        {{`{{- end }}`}}
        {{`{{- end }}`}}
        {{`{{- end }}`}}
        {{- else }}
        {{/* Book/chapter has auto-sync enabled - check spell override */}}
        {{`{{- if .appParams.disableAutoSync }}`}}
        {{/* Spell explicitly disables auto-sync */}}
        {{`{{- else }}`}}
        {{/* Auto-sync enabled - use spell value or default */}}
        {{`{{- if .appParams.syncPolicy.automated }}`}}
        automated:
          '{{`{{- toYaml .appParams.syncPolicy.automated | nindent 10 }}`}}'
        {{`{{- else }}`}}
        automated:
{{- toYaml $chapterAppParams.syncPolicy.automated | nindent 10 }}
        {{`{{- end }}`}}
        {{`{{- end }}`}}
        {{- end }}
        {{/* syncOptions - use spell value or default */}}
        {{`{{- if and .appParams .appParams.syncPolicy.syncOptions }}`}}
        {{/* Spell has custom syncOptions */}}
        syncOptions:
          '{{`{{- toYaml .appParams.syncPolicy.syncOptions | nindent 10 }}`}}'
        {{`{{- else }}`}}
        {{/* Use default syncOptions (book + chapter merged) */}}
        syncOptions:
{{- toYaml $chapterAppParams.syncPolicy.syncOptions | nindent 10 }}
        {{`{{- end }}`}}
        {{/* retry - use spell value or default */}}
        {{`{{- if and .appParams .appParams.syncPolicy.retry }}`}}
        {{/* Spell has custom retry config */}}
        retry:
          '{{`{{- toYaml .appParams.syncPolicy.retry | nindent 10 }}`}}'
        {{`{{- else }}`}}
        {{/* Use default retry config (book + chapter merged) */}}
        retry:
{{- toYaml $chapterAppParams.syncPolicy.retry | nindent 10 }}
        {{`{{- end }}`}}
      {{`{{- $ignoreDiff := list }}`}}
      {{`{{- if and .appParams .appParams.ignoreDifferences }}`}}
      {{`{{- $ignoreDiff = .appParams.ignoreDifferences }}`}}
      {{`{{- end }}`}}
      {{`{{- range .runes }}`}}
        {{`{{- if and .appParams .appParams.ignoreDifferences }}`}}
        {{`{{- $ignoreDiff = concat $ignoreDiff .appParams.ignoreDifferences }}`}}
        {{`{{- end }}`}}
      {{`{{- end }}`}}
      {{`{{- if $ignoreDiff }}`}}
      ignoreDifferences:
        '{{`{{- toYaml $ignoreDiff | nindent 8 }}`}}'
      {{`{{- end }}`}}
{{- end }}
