# Comprehensive Vault Glyph TDD Test
# Tests all vault secret parameters through kaster system

spellbook:
  name: example-tdd-book
chapter:
  name: infrastructure

# Test vault lexicon configuration
lexicon:
  - chapter: infrastructure
    skipVerify: true
    type: vault
    url: http://vault.vault.svc:8200
    namespace: vault
    serviceAccount: vault
    authPath: k8s-path-auth
    secretPath: kv
    labels:
      default: book

namespace: vault-test

glyphs:
  vault:
    # TEST 1: Path Resolution Variants
    - type: secret
      name: book-level-secret
      path: "book"
      format: plain
      keys:
        - username
        - password

    - type: secret
      name: chapter-level-secret
      path: "chapter"
      format: plain
      keys:
        - api-key
        - token

    - type: secret
      name: absolute-path-secret
      path: "/shared/credentials"
      format: plain
      keys:
        - database-url
        - redis-url

    - type: secret
      name: summon-level-secret
      format: plain
      keys:
        - service-key
        - endpoint

    # TEST 2: Format Variants
    - type: secret
      name: env-format-secret
      format: env
      keys:
        - database-url
        - api-key
        - service-port
      staticData:
        environment: production
        region: us-east-1

    - type: secret
      name: json-format-secret
      format: json
      key: config-json

    - type: secret
      name: b64-format-secret
      format: b64
      key: encoded-data

    - type: secret
      name: yaml-format-secret
      format: yaml
      key: config-yaml

    - type: secret
      name: plain-format-secret
      format: plain
      keys:
        - username
        - password
        - host
      staticData:
        port: "5432"
        ssl: "true"

    # TEST 3: Random Secrets
    - type: secret
      name: basic-random-secret
      format: plain
      random: true
      keys:
        - username
      staticData:
        database: postgres

    - type: secret
      name: custom-random-key-secret
      format: plain
      randomKey: admin-password
      keys:
        - service-name
      staticData:
        environment: staging

    - type: secret
      name: random-env-format-secret
      format: env
      random: true
      keys:
        - database-host
        - database-port
      staticData:
        ssl-mode: require

    # TEST 4: Advanced Options
    - type: secret
      name: custom-sa-secret
      format: plain
      serviceAccount: custom-vault-sa
      keys:
        - token
      refreshPeriod: 5m0s

    - type: secret
      name: tls-secret
      format: plain
      secretType: kubernetes.io/tls
      keys:
        - tls.crt
        - tls.key

    - type: secret
      name: metadata-secret
      format: plain
      keys:
        - api-key
      annotations:
        vault.io/source: "external-secrets"
        reloader.stakater.com/match: "true"
      labels:
        app: my-application
        tier: backend
        environment: production

    # TEST 5: Edge Cases
    - type: secret
      name: special-chars-secret
      format: env
      keys:
        - "api-key"
        - "database.host"
        - "service-port"
      staticData:
        special-value: "with-dashes"

    - type: secret
      name: static-only-secret
      format: env
      staticData:
        database-type: postgres
        connection-pool-size: "20"
        max-connections: "100"

    - type: secret
      name: minimal-secret
      # All other values should use defaults