---
apiVersion: redhatcop.redhat.io/v1alpha1
kind: PasswordPolicy
metadata:
  name: simple-password-policy
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  # Add fields here
  authentication:
    path: control-plane
    role: vault
    serviceAccount:
      name: vault
  connection:
    address: http://vault.vault.svc:8200
    tLSConfig:
      skipVerify: true
  passwordPolicy: |
    length = 36
    rule "charset" {
      charset = "abcdefghijklmnopqrstuvwxyz"
      min-chars = 3
    }
    rule "charset" {
      charset = "ABCDEFGHIJKLMNOPQRSTUVWXYZ"
      min-chars = 3
    }
    rule "charset" {
      charset = "0123456789"
      min-chars = 3
    }
    # rule "charset" {
    #   charset = "#%~^_-+=.,:?"
    #   min-chars = 3
    # }