name: deployment-free-deck

deckReadout:
  deckVolume:
    worldDefinitions:
      type: emptyDir
      size: 1Gb
      path: /worldDefinitions
  sealedDeck: #contaienrSet [sealedDeck, openTable(dag), others??]
    - card: git-clone
      base: git
      command: |
        git clone spellbook
        git clone repo
    - card: build
      base: buildah #como es card este base es el nombre de una card definida en el deckPile
      dependancies:
        - git-clone
      command: |
        buildah build
    - deckReadout: tests
      base: tests #seria el nombre del workflow en este caso
      dependancies:
        - git-clone
    - card: argocdUpdater
      base: git
      command: |
        git push
        argocd-refresh
      dependancies:
        - tests
        - build
    - deckReadout: afterDeploy #afterChabon
      dependancies:
        - argocdUpdater

volumes:

secrets:
  github-token:
    type: secret
    values:
      type: env
      name: gh-token
      keys:
        - ghGithub