apiVersion: external-secrets.io/v1alpha1
kind: ClusterSecretStore
metadata:
  name: secret-generator
  namespace: unity
spec:
  provider:
    vault:
      server: https://vault-alter.dev.soytul.com
      path: "kv"
      version: "v2"
      auth:
        kubernetes:
          mountPath: cluster-control
          role: unity
          serviceAccountRef:
            name: unity
            namespace: unity
---
apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: bitbucket
  namespace: unity
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: secret-generator
    kind: ClusterSecretStore
  target:
    name: bitbucket
  dataFrom:
  - key: workflows/bitbucket

