{{/*kast - Kubernetes arcane spelling technology
Copyright (C) 2023 namenmalkv@gmail.com
Licensed under the GNU GPL v3. See LICENSE file for details.
 */}}
{{- $root := . }}{{/* esto seria remplazable por $ pero para lectura de codigo */}} 
---
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMServiceAccount
metadata:
  annotations:
    cnrm.cloud.google.com/project-id: {{ $root.Values.projectID }}
  labels:
    createdby: "config-connector"
    managedBy: "kast-{{ $root.Values.name }}"
    project: {{ $root.Values.projectID }}
  name: kast-{{ $root.Values.name }}
spec:
  displayName: Kast Control Plane
  description: Used by kast fot infrastruture managment on {{ $root.Values.name }} Project
---
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMServiceAccount
metadata:
  annotations:
    cnrm.cloud.google.com/project-id: {{ $root.Values.projectID }}
  labels:
    createdby: "config-connector"
    managedBy: "kast-{{ $root.Values.name }}"
    project: {{ $root.Values.projectID }}
  name: {{ $root.Values.projectID }}-cert-mgr
spec:
  displayName: {{ $root.Values.name }}-cert-manager
  description: used by cert-manager and external-dns on the {{ $root.Values.name }} cluster
