{{/*kast - Kubernetes arcane spelling technology
Copyright (C) 2023 namenmalkv@gmail.com
Licensed under the GNU GPL v3. See LICENSE file for details.
 */}}
{{- $root := . }}{{/* esto seria remplazable por $ pero para lectura de codigo */}} 
apiVersion: resourcemanager.cnrm.cloud.google.com/v1beta1
kind: Project
metadata:
  annotations:
    cnrm.cloud.google.com/project-id: {{ $root.Values.projectID }}
  labels:
    createdby: "config-connector"
    managedby: "kast-{{ $root.Values.name }}"
    project: {{ $root.Values.projectID }}
  name: {{ $root.Values.projectID }}
spec:
  name: {{ $root.Values.projectID }}
  folderRef:
    external: {{ $root.Values.folderID | quote }}
  # organizationRef:
  #   external: {{ $root.Values.orgID | quote }}
    