 {{/*kast - Kubernetes arcane spelling technology
Copyright (C) 2023 namenmalkv@gmail.com
Licensed under the GNU GPL v3. See LICENSE file for details.
 */}}
{{- $root := . }}{{/* esto seria remplazable por $ pero para lectura de codigo */}} 

{{- if $root.Values.sentence.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: {{ $root.Values.name }}-{{ $root.Values.serviceAccount.name }}-template
spec:
  entrypoint: deploy
  arguments:
    parameters:
    {{- range $root.Values.parameters }}
      {{-  . | toYaml| nindent 6 }}
    {{- end }}
  templates:
    - name: deploy
      volumes:
      {{- range $cantrip := $root.Values.sentence.cantrips }}
      {{- include "summon.common.volumes" $root | nindent 8}}
      {{- end}}
        - name: repo-volume
          emptyDir:
            sizeLimit: 1Gi
        - name: ssh-key-volume
          secret:
            secretName: kast01-ssh
            defaultMode: 0600
      containerSet:
        volumeMounts:
          - name: repo-volume
            mountPath: /repo
        containers:
        {{- range $cantripName, $cantrip := $root.Values.sentence.cantrips }}
          {{- if $cantrip.verb }}
          {{- $content := include (printf "default-verbs.%s" $cantrip.verb ) (list $root $cantripName $cantrip ) }}
          {{- include "summon.common.container" (list $root $cantripName $content ) | nindent 8 }}
            
          {{ else }}
        - print: MALLLLAAA
            {{- include "summon.common.container" (list $root $cantripName $cantrip ) | nindent 8 }}
          {{- end }}

        {{- end }}

{{- end }}
