{{- if .Values.sentence.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: {{ .Values.name }}
spec:
  entrypoint: deploy
  templates:
    - name: deploy
      dag:
        tasks:
          {{- $cantrips := .Values.sentence.cantrips }}
          {{- $prev := "" }}
          {{- range $index, $step := $cantrips }}
          - name: {{ $step.name }}
            {{- if $index }}
            dependencies: [{{ $prev }}]
            {{- end }}
            {{- if $step.workflow }}
            templateRef:
              name: {{ $step.workflow.name }}
              template: {{ $step.workflow.template }}
            arguments:
              parameters:
                {{- range $key, $val := $step.workflow.parameters }}
                - name: {{ $key }}
                  value: {{ $val | quote }}
                {{- end }}
            {{- else }}
            template: {{ $step.name }}-template
            {{- end }}
          {{- $prev = $step.name }}
          {{- end }}

          - name: final-check
            dependencies:
              {{- range $step := $cantrips }}
              - {{ $step.name }}
              {{- end }}
            template: final-verification

    {{- range $step := .Values.sentence.cantrips }}
    {{- if not $step.workflow }}
    - name: {{ $step.name }}-template
      container:
        image: {{ $step.image }}
        command: ["sh", "-c"]
        args: [{{ $step.command | quote }}]
    {{- end }}
    {{- end }}

    - name: final-verification
      container:
        image: busybox
        command: ["sh", "-c"]
        args: ["echo '✅ All done!'"]
{{- end }}
