# Info on GitHub Webhook: https://developer.github.com/v3/repos/hooks/#create-a-hook
apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: github
spec:
  eventBusName: pipeline
  service:
    ports:
      - name: githook
        port: 12000
        targetPort: 12000
  github:
    githook:
      repositories:
        - owner: kast-spells
          # names:
          #   - argo-events
          #   - argo-workflows
      webhook:
        endpoint: /push
        port: "12000"
        method: POST
        url: https://the.yaml.life/push
      events:
        - "*"
      # insecure: false
      active: true
      contentType: json

      webhookSecret:
       # Name of the K8s secret that contains the hook secret
       name: github-secret
       # Key within the K8s secret whose corresponding value (must be base64 encoded) is hook secret
       key: password
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: github-sarasa-svc
spec:
  gateways:
    - yaml-gw/yaml-external
    - mesh
  hosts:
    - the.yaml.life
  http:
    - match:
        - uri:
            prefix: /push
      route:
        - destination:
            host: github-eventsource-svc
            port:
              number: 12000

