apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: webhook-sarasa-svc
spec:
  gateways:
    - yaml-life-int-gw/yaml-life-int-gw
    - mesh
  hosts:
    - int.the.yaml.life
  http:
    - match:
        - uri:
            prefix: /pepe
      route:
        - destination:
            host: webhook-sarasa-eventsource-svc
            port:
              number: 12000
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: argocd-yaml-life-int-gw
spec:
  gateways:
    - yaml-life-int-gw/yaml-life-int-gw
    - mesh
  hosts:
    - pepe.int.the.yaml.life
  http:
    - match:
        - uri:
            prefix: /
      route:
        - destination:
            host: webhook-sarasa-eventsource-svc
            port:
              number: 12000
