apiVersion: v2
name: librarian
description: librarian Argo CD Apps of Apps for runik
version: "1.2.4"
home: https://github.com/runik-spells
sources:
  - https://github.com/runik-spells/runik-system
maintainers:
  - name: namen malkav
    email: namenmalkav@gmail.com
  - name: laaledesiempre
    email: laaledesiempre@disroot.org