{{- $root := . }}
# sa for workflow

{{- define "ksa.inline" }}
enabled: true
{{- end }}
{{- $ksaDefinition := include "ksa.inline" $root | fromYaml  }}
{{- include "summon.serviceAccount" (list $root $ksaDefinition ) }}


