eventBus:
  enabled: true
  name: control-plane-default
  replicas: 1
rbac:
  enabled: true
seviceAccount:
  name: github
name: github
sensor:
  enabled: true
  branch: main
 
configMaps: {}
workflow:
  name: github
  enabled: false
  containers:
    cursed:
      dependancies: #they can have dependancies to set complex of the cantrip sentence
        - canHaveAVerb
      image:
        name: busybox #or have full custom container configuration
      command: [sh, -c]
      args: ["sleep 10 && ls /repo"]
      probes: {}
      resources:
        limits:
          cpu: "10m"
          memory: "20M"
        requests:
          cpu: "10m"
          memory: "10M"
      volumes:
        config:
          type: hostPath
          destinationPath: /config
          path: /mnt/storage/cargo-hold/retriever/transmission-config
      secrets:
        kast01-ssh:
          type: file
          mountPath: /key.pem
          defaultMode: 0600
eventSource:
  enabled: true
  name: github
  endpoint: ""
  url: cosa.the.yaml.com

parameters:
  - name: gitURL
    value: git@github.com
  - name: orgName
    value: the-yaml-life
  - name: containerFileName
    value: Containerfile
  - name: spellbook
    value: the-recolection-of-BOBs-spells
  - name: spellbookRepo
    value: the-library
  - name: spellbookBranch
    value: master
  - name: chapterName
    value: testing
  - name: spellName
    value: ms-default-landing