eventBus:
  enabled: true
  name: control-plane-default
  replicas: 1
rbac:
  enabled: true
seviceAccount:
  name: github

sensor:
  enabled: true
configMaps: {}
workflow:
  enabled: true
  containers:
    cursed:
      dependancies: #they can have dependancies to set complex of the cantrip sentence
        - canHaveAVerb
      image:
        name: busybox #or have full custom container configuration
      command: [sh, -c]
      args: ["sleep 10 && ls /repo"]
      probes: {}
      resources:
        limits:
          cpu: "10m"
          memory: "20M"
        requests:
          cpu: "10m"
          memory: "10M"


eventSource:
  enabled: true
  name: github
  endpoint: ""
  url: cosa.the.yaml.com

parameters:
  - name: gitURL
    value: git@github.com
  - name: orgName
    value: the-yaml-life
  - name: containerFileName
    value: Containerfile
  - name: spellbook
    value: the-recolection-of-BOBs-spells
  - name: spellbookRepo
    value: https://github.com/the-yaml-life/the-recolection-of-BOBs-spells
  - name: spellbookBranch
    value: master
  - name: chapterName
    value: testing
  - name: spellName
    value: ms-default-landing