{{- $root := . }}{{/* esto seria remplazable por $ pero para lectura de codigo */}} 

{{- if $root.Values.workflow.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: ClusterWorkflowTemplate
metadata:
  name: {{ $root.Values.name }}-{{ $root.Values.workflow.name }}
spec:
  entrypoint: deploy
  arguments:
    parameters:
      - name: branch
        value: hello world
      - name: repo
        value: ACAA
  {{- $root.Values.parameters | toYaml| nindent 6 }}
  templates:
    - name: deploy
      {{- range $containerName, $container  := $root.Values.workflow.containers }}
      {{- include "summon.common.volumes" $container | nindent 6}}
      {{- end}}
        - name: repo-volume
          emptyDir:
            sizeLimit: 1Gi
      containerSet:
        volumeMounts:
          - name: repo-volume
            mountPath: /repo
        containers:
        {{- range $containerName, $container := $root.Values.workflow.containers }}
          {{- if $container.card }}
          {{- $content := include (printf "default-card.%s" $container.card ) (list $root $containerName $container ) }} 
          ## TODO esto tiene q ser solo un merge pero un runic selector desde otro lexicon o algo asi con todas las card definition
          {{- include "summon.common.container" (list $root $containerName $content ) | nindent 8 }}  
          {{ else }}
            {{- include "summon.common.container" (list $root $containerName $container ) | nindent 8 }}
          {{- end }}

        {{- end }}

{{- end }}
