{{- range $index, $globlBytes := .Values.secrets }}
{{ $secret := index $.Values.secrets $index -}}
---
apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: {{ $secret.name }}
  namespace: {{ $secret.namespace }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: {{ default $.Values.unityPlugin.name $.Values.unityPlugin.override }}
    kind: ClusterSecretStore
  target:
    name: {{ $secret.name }}
{{- if $secret.template }}
    template:
      data:
        config: |-
          {{ $secret.template.config }}
  data:
 {{- range $propertyIndex := $secret.template.properties }}
  - secretKey: {{ $propertyIndex }}
    remoteRef:
      key: {{ $secret.path }}
      property: {{ $propertyIndex }}
{{ end }}
{{ else }}
  dataFrom:
  - key: {{ $secret.path }}
{{- end -}}
{{ end -}}