{{- $root := . }}

# rbac (probably)
# confirmar q la ksa de la app pueda  pulleawer

# gcp.sa-asoc
{{- define "iamBind.inline" }}
{{- $root := . }}
name: {{ $root.Values.name }}-registry
member: serviceAccount:{{ $root.Values.projectID }}.svc.id.goog[{{ $root.Release.Namespace }}/{{ include "common.name" $root  }}]
resourceRef:
  apiVersion: artifactregistry.cnrm.cloud.google.com/v1beta1
  kind: ArtifactRegistryRepository
  name: {{ $root.Values.name }}-registry
role: roles/artifactregistry.admin

{{- end }}

{{- $gsaDefinition := include "iamBind.inline" $root | fromYaml }}
{{- include "gcp.iamBind" (list $root $gsaDefinition ) }}

# sa for workflow

{{- define "ksa.inline" }}
enabled: true
{{- end }}
{{- $ksaDefinition := include "ksa.inline" $root | fromYaml  }}
{{- include "summon.serviceAccount" (list $root $ksaDefinition ) }}

# registry repo # registry cleanup
{{- if $root.Values.registry.enabled }}
apiVersion: artifactregistry.cnrm.cloud.google.com/v1beta1
kind: ArtifactRegistryRepository
metadata:
  name: {{ $root.Values.name }}-registry
  labels:
    {{- include "common.infra.labels" $root | nindent 4}}
  annotations:
    {{- include "common.infra.annotations" $root | nindent 4}}
spec:
  {{- if $root.Values.registry.cleanup.enabled }}    
  cleanupPolicies:
  - action: delete
    id: {{ $root.Values.registry.cleanup.id }}
    {{- if not $root.Values.registry.cleanup.keepNum }}
    condition:
      olderThan: {{ $root.Values.registry.cleanup.olderThan }}
    {{- else }}
    mostRecentVersions:
      keepCount: {{ $root.Values.registry.cleanup.keepNum }}
    {{- end }}
  {{- end }}
  description: {{ $root.Values.registry.name }}
  dockerConfig:
    immutableTags: {{ $root.Values.registry.immutableTags }}
  location: {{ $root.Values.registry.location }}
  format: Docker
{{- end }}