{{- $root := . }}{{/* esto seria remplazable por $ pero para lectura de codigo */}} 
{{ if $root.Values.rbac.enabled }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ $root.Values.name }}-{{ $root.Values.seviceAccount.name }}-sensor
rules:
- apiGroups: [""]
  resources: ["pods", "pods/log", "services", "endpoints", "persistentvolumeclaims"]
  verbs: ["create", "delete", "get", "list", "watch", "update", "patch"]
- apiGroups: ["batch"]
  resources: ["jobs"]
  verbs: ["create", "delete", "get", "list", "watch", "update", "patch"]
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["create", "delete", "get", "list", "watch", "update", "patch"]
- apiGroups: ["argoproj.io"]
  resources: ["workflows"]
  verbs: ["create", "delete", "get", "list", "watch", "update", "patch"]
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["create", "delete", "get", "list", "watch", "update", "patch"]
- apiGroups: ["argoproj.io"]
  resources: ["workflowtaskresults"]
  verbs: ["create", "get", "update", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ $root.Values.name }}-{{ $root.Values.seviceAccount.name }}-sensor
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ $root.Values.name }}-{{ $root.Values.seviceAccount.name }}-sensor #por q debe de ser diferente de la de 
subjects:
- kind: ServiceAccount
  name: {{ $root.Values.name }}-{{ $root.Values.seviceAccount.name }}-sensor
  namespace: {{ $root.Release.Namespace }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $root.Values.name }}-{{ $root.Values.seviceAccount.name }}-sensor
spec:
{{- end }}