{{- $root := . }}

{{- if $root.Values.sensor.enabled }}
---
apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: github-deploy-sensor
spec:
  eventBusName: {{ $root.Values.eventBus.name }}
  template:
    serviceAccountName: {{ $root.Values.name }}-{{ $root.Values.seviceAccount.name }}-sensor
    container:
      resources:
        requests:
          memory: "16Mi"
          cpu: "10m"
        limits:
          memory: "32Mi"
          cpu: "20m"
  dependencies:
    - name: github-push
      eventSourceName: {{ $root.Values.eventSource.name }}
      eventName: githook
      # filters:
      #   exprs:
      #     - expr: name == "pepe"
      #       fields:
      #         - name: name
      #           path: body.nombre
  triggers:
    # PUSH: Cualquier push excepto develop
    - template:
        name: trigger-on-push
        # conditions: >-
        #   parseJSON(github-push.payload).ref != 'refs/heads/{{ $root.Values.sensor.branch }}' &&
        #   parseJSON(github-push.payload).head_commit != null
        k8s:
          group: argoproj.io
          version: v1alpha1
          resource: workflows
          operation: create
          source:
            resource:
              apiVersion: argoproj.io/v1alpha1
              kind: Workflow
              metadata:
                generateName: {{ $root.Values.name }}-{{ $root.Values.workflow.name }}-
              spec:
                workflowTemplateRef:
                  name: {{ $root.Values.name }}-{{ $root.Values.workflow.name }}-template
                  clusterScope: true
                arguments:
                  parameters:
                    - name: branch
                      value: hello world
                    - name: repo
                      value: git@github.com
                    - name: gitURL
                      value: git@github.com
                    - name: orgName
                      value: the-yaml-life
                    - name: containerFileName
                      value: Containerfile
                    - name: spellbook
                      value: the-recolection-of-BOBs-spells
                    - name: spellbookRepo
                      value: https://github.com/the-yaml-life/the-recolection-of-BOBs-spells
                    - name: spellbookBranch
                      value: master
                    - name: chapterName
                      value: testing
                    - name: spellName
                      value: ms-default-landing
        parameters:
          - src:
              dependencyName: github-push
              dataKey: body.branch
            dest: spec.arguments.parameters.0.value
          - src:
              dependencyName: github-push
              dataKey: body.repo
            dest: spec.arguments.parameters.1.value
          # - src:
          #     dependencyName: test-dep
          #     dataKey: body.wf
          #   dest: spec.workflowTemplateRef.name
{{- end }}


