{{- $root := . }}

{{- if $root.Values.sensor.enabled }}
---
apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: github-deploy-sensor
spec:
  eventBusName: {{ $root.Values.eventBus.name }}
  template:
    serviceAccountName: {{ $root.Values.name }}-{{ $root.Values.seviceAccount.name }}-sensor
    container:
      resources:
        requests:
          memory: "16Mi"
          cpu: "10m"
        limits:
          memory: "32Mi"
          cpu: "20m"
  dependencies:
    - name: github-push
      eventSourceName: {{ $root.Values.eventSource.name }}
      eventName: githook
      filters:
        exprs:
          - expr: revision == "refs/heads/main"
            fields:
              - name: revision
                path: body.ref
  triggers:
    - template:
        name: trigger-on-push
        # conditions: >-
        #   parseJSON(github-push.payload).ref != 'refs/heads/{{ $root.Values.sensor.branch }}' &&
        #   parseJSON(github-push.payload).head_commit != null
        k8s:
          group: argoproj.io
          version: v1alpha1
          resource: workflows
          operation: create
          source:
            resource:
              apiVersion: argoproj.io/v1alpha1
              kind: Workflow
              metadata:
                generateName: {{ $root.Values.name }}-{{ $root.Values.workflow.name }}-
                namespace: {{ default $root.Release.Namespace $root.Values.workflow.namespace }}
                # labels:
                #   argocd.argoproj.io/instance: {{ default $root.Release.Name $root.Values.overWriteInstance }}
              spec:
                workflowTemplateRef:
                  name: {{ $root.Values.name }}-{{ $root.Values.workflow.name }}-template
                  clusterScope: true
                arguments:
                  parameters:
                    - name: revision
                      value: hello world
                    - name: repository
                      value: defaultLanding
                    - name: orgName
                      value: the-life
                    - name: eventType
                      value: push
      parameters:
        - src:
            dependencyName: github-push
            dataKey: body.ref
          dest: k8s.source.resource.spec.arguments.parameters.0.value
          # Este valor será 'refs/heads/develop'
        - src:
            dependencyName: github-push
            dataKey: body.repository.name
          dest: k8s.source.resource.spec.arguments.parameters.1.value
        - src:
            dependencyName: github-push
            dataKey: body.repository.owner.name
          dest: k8s.source.resource.spec.arguments.parameters.2.value
      # - src:
      #     dependencyName: github-push
      #     dataKey: headers.X-GitHub-Event
      #   dest: spec.arguments.parameters.3.value
{{- end }}


