
{{- $root := . }}

# Info on GitHub Webhook: https://developer.github.com/v3/repos/hooks/#create-a-hook
{{- if $root.Values.eventSource.enabled }}
---
apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: {{ $root.Values.eventSource.name }}
spec:
  eventBusName: {{ $root.Values.eventBus.name }}
  service:
    ports:
      - name: githook
        port: 12000
        targetPort: 12000
  github: #esto era un algo random??
    githook: #o era este?
      repositories:
        - owner: {{ $root.Values.githubOrganization }}
      webhook:
        endpoint: /{{ $root.Values.eventSource.endpoint}}
        port: "12000"
        method: POST
        url: {{ $root.Values.eventSource.url }}/{{ $root.Values.eventSource.endpoint}}
      {{- with $root.Values.eventSource.events }}
        - {{ . }}
      {{- else }} 
      events:
        - "*"
      {{- end }}
      # insecure: false
      active: {{ $root.Values.eventSource.enabled }}
      contentType: {{ default "json" $root.Values.eventSource.contentType }}

      webhookSecret:
       # Name of the K8s secret that contains the hook secret
       name: {{ $root.Values.eventSource.name }}-webhook-auth
       # Key within the K8s secret whose corresponding value (must be base64 encoded) is hook secret
       key: password
# ---
# apiVersion: networking.istio.io/v1alpha3
# kind: VirtualService
# metadata:
#   name: github-sarasa-svc
# spec:
#   gateways:
#     - yaml-gw/yaml-external
#   hosts:
#     - yaml.life
#   http:
#     - match:
#         - uri:
#             prefix: /push
#       route:
#         - destination:
#             host: github-eventsource-svc
#             port:
#               number: 12000
{{- end }}
