name: Sync Code to Another Repo and Create Release

on:
  push:
    tags:
      - "summon-*" # Se ejecuta cuando hay un nuevo tag en el repo origen

jobs:
  summon-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source repository
        uses: actions/checkout@v4

      - name: Extract tag name
        id: get_tag
        run: echo "TAG_NAME=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Clone destination repository
        run: |
          git clone https://x-access-token:${{ secrets.DEST_REPO_PAT }}@github.com/kast-spells/summon.git summon-repo
          cd summon-repo
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Copy files to destination repository
        run: |
          shopt -s extglob
          rm -rf summon-repo/!(.git)
          cp -rL charts/summon/* summon-repo/
          CHART_VERSION=$(echo $TAG_NAME | sed 's/summon-//')
          sed -i "s/^version:.*/version: ${CHART_VERSION}/" summon-repo/Chart.yaml

      - name: Create tag in destination repository
        run: |
          cd summon-repo
          if git rev-parse "$TAG_NAME" >/dev/null 2>&1; then
            echo "Tag $TAG_NAME already exists. Skipping..."
          else
            git add .
            git commit -m "Release - Tag: $TAG_NAME"
            git push origin master
            git tag "$TAG_NAME"
            git push origin "$TAG_NAME"
          fi